#' Writes a PHYLIP-formatted file of fully concatenated gene datasets and an
#' associated partition file for RAxML concatenated phylogenetic analysis
#'
#' @author Domingos Cardoso, Quezia Cavalcante, and Bruno Vilela
#'
#' @description from the resulting list of equally-sized dataframes containing the
#' input gene datasets, as generated by the functions \code{\link{catfullGenes}}
#' or \code{\link{catmultGenes}}, it will write (i) a final PHYLIP-formatted file
#' of fully concatenated gene datasets and (ii) an associated partition file for
#' the RAxML concatenated phylogenetic analysis using a mixed/partitioned model.
#'
#' @usage
#' writePhylip(x,
#'            file,
#'            catalignments = TRUE,
#'            partitionfile = TRUE)
#'
#' @param x The object to be written, a list of equally-sized dataframes containing
#' the input gene datasets, as generated by the functions \\code{\link{catfullGenes}}
#' or \code{\link{catmultGenes}}.
#'
#' @param file Either a character string naming a file or a \code{\link{connection}}
#'  open for writing.
#'
#' @param catalignments Logical, if \code{FALSE} will not write the concatednated
#' matrix of DNA alinments. Better to keep it always as \code{TRUE}.
#'
#' @param partitionfile Logical, if \code{FALSE} will not write the associated
#' text-formatted partition file for the RAxML concatenated phylogenetic analysis
#' using a mixed/partitioned model.
#'
#' @seealso \code{\link{catfullGenes}}
#' @seealso \code{\link{catmultGenes}}
#'
#' @examples \dontrun{
#' data(Gaya)
#' df <- catfullGenes(Gaya,
#'                    shortaxlabel = TRUE,
#'                    missdata = FALSE,
#'                    outgroup = "Abutilon_costicalyx")
#'
#' writePhylip(df,
#'             file = "filename.phy",
#'             catalignments = TRUE,
#'             partitionfile = TRUE)
#' }
#'
#' @importFrom R.utils insert
#' @importFrom tidyr unite
#' @importFrom utils write.table
#'
#' @export

writePhylip <- function(x, file,
                        catalignments = TRUE,
                        partitionfile = TRUE) {

  datset <- .namedlist(x)

  numberinputdatset <- length(datset)

  # Unlist and rename an input list from genefullcomp function
  if (numberinputdatset == 1) {
    datset <- unlist(datset, recursive = FALSE)
    names(datset) <- gsub(".*[.]", "", names(datset))

    for (i in 1:length(datset)) {
      datset[[i]]$species <- as.character(datset[[i]]$species)
      datset[[i]]$sequence <- as.character(datset[[i]]$sequence)}
  }

  numberdatset <- length(datset)

  if (numberdatset == 1){
    stop("You must provide a file generated by the genefullcomp
          Find help also at DBOSLab-UFBA (Domingos Cardoso; cardosobot@gmail.com)")
  }

  genenames <- names(datset)

  cat("You are combining the following gene datasets:", "", sep = "\n")
  cat(cat(genenames, sep = ", "), "", sep = "\n")
  cat(cat("Total number of datasets:", numberdatset), "", sep = "\n")

  numbchar <- lapply(datset, function(x) nchar(x[1, 2]))
  series_numbchar <- paste(lapply(numbchar, function(x) unlist(x)))

  # Making all separate dataset within the list the same size to transforme into a dataframe with NAs whenever there is no sequence
  #datasets <- lapply(datasets, `length<-`, max(lengths(datasets)))

  ntax <- paste0(length(rownames(datset[[1]])))
  nchartotal <- sum(unlist(numbchar))

  dimensions <- paste(ntax, nchartotal, sep = " ")

  cat("Your phylip-formatted concantenated dataset will have the following DIMENSIONS:", "", sep = "\n")
  cat(paste(ntax, "TAXA"), sep = "\n")
  cat(paste(nchartotal, "CHARACTERS"), sep = "\n")

  # Calculating the space between the taxon labels and corresponding DNA sequence for each dataset
  # First calculate how many letters in each taxon in each dataset
  letrs_taxlabs <- lapply(datset, function(x) nchar(x$species))

  # Setting the maximum of space based on the largest taxonlabel
  maxletrs_taxlabs <- lapply(letrs_taxlabs, function(x) max(x)+5) # Just increase this last number if we want to add more space
  maxletrs_taxlabs <- max(unlist(maxletrs_taxlabs))


  # We can also pad a string inside a list of dataframes by adding numbers or names at any position in the specific column
  f_b <- function(x, y) {
    for (i in 1:length(x$species)) {
      x$species[i] <- paste0(x$species[i], paste0(rep(" ", y - nchar(x$species[i])),
                                                  collapse = ""))
    }
    x
  }
  datset <- lapply(datset, f_b,
                   y = maxletrs_taxlabs)

  # Uniting the two columns inside just the first dataframe
  datset[[1]] <- tidyr::unite(datset[[1]], "sequences", colnames(datset[[1]]), sep = " ")

  # Deleting the species collumn in the remaining dataset
  for (i in 2:numberdatset){
    datset[[i]] <- data.frame(sequences=datset[[i]][,2])
  }

  ex_datset <- do.call("cbind", datset)
  names(ex_datset) <- paste("sequences", 1:length(ex_datset), sep = "")

  # Uniting all columns
  genes <- tidyr::unite(ex_datset, "sequences", sep = "")

  genes$sequences <- as.character(genes$sequences)

  cat("Concatenating the genes...", "", sep = "\n")

  #n <- dim(genes)[1]
  #genes <- genes[1:(n-3),] # To remove few paragraphs after the matrix block and before the "; END;"
  colnames(genes) <- paste(dimensions,
                           sep = "\n")

  if(catalignments){
    # Writing the concatenated dataset
    zz <- file(file, "w")
    write.table(genes, zz,
                append = FALSE, quote = FALSE, sep = " ",
                eol = "\n", na = "", dec = ".", row.names = FALSE,
                col.names = TRUE)
    close(zz)
  }


  # Creating the txt file for a mixed/partitioned model in RAxML
  partitionnames <- paste0("gene", 1:length(genenames))
  charsets <- paste(rep("DNA,", times = numberdatset), partitionnames, "= ")

  # Calculating the end of each gene with a cumulative sum of each gene size
  endgene <- paste(cumsum(series_numbchar))

  # Calculating the begining of each gene
  startgene <- lapply(as.numeric(endgene), function(x) x+1)

  # Dropping last value in the list
  startgene <- startgene[1:(length(startgene)-1)]

  # Insert the number "1" in the first position of the list
  startgene <- paste(R.utils::insert(startgene, ats = 1, values = 1))

  partitions <- paste0(charsets,
                       startgene,
                       rep("-", times = numberdatset),
                       endgene,
                       sep = "\n")
  partitions <- paste(partitions, collapse = "")
  partitions <- data.frame(partitions)


  if (partitionfile) {
    # Writing the partition file for RAxML concatenated analysis
    if (catalignments) {
    zy <- file(paste0(sub("[.].*", "", file), "_partition_file.txt"), "w")
    } else {
    zy <- file(file, "w")
    }
    write.table(partitions, zy,
                append = FALSE, quote = FALSE, sep = " ",
                eol = "\n", na = "", dec = ".", row.names = FALSE,
                col.names = FALSE)
    close(zy)

  }

  cat("Gene concatenation is finished!", "",
      sep = "\n")

  if(!catalignments & partitionfile){
    cat("But you downloaded just the partition file...",
        sep = "\n")
    cat("Run the function again, making sure to have \"catalignments = TRUE\".",
        sep = "\n")
  }
}
